DROP TABLE IF EXISTS hostpital;

CREATE TABLE hospital (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    address TEXT NOT NULL,
    phone VARCHAR(10) NOT NULL
);
